### ISSUE TITLE
This was almost perfect

### ISSUE THREAD

**Issue by Prid13** [dariober/excelToCsv#1]
Loved the relatable text, loved all the points and shared many of the cumbersome issues myself, loved that it converts both xlsx _and_ xls, but then it said that Java installation is required to run this :(

Is there a way to make this completely self-contained, so that no external dependencies are needed to run it? :)

**Comment by dariober** [comment]
@Prid13 Thanks! 

> Is there a way to make this completely self-contained, so that no external dependencies are needed to run it? :)

To the best of my knowledge, the answer is no. Not just for this program but really for *any* program. Eventually, the developer has to set some requirements for the user. It may be the user's operating system, or some libraries available there. Docker aims at creating fully self-contained environments, but then docker itself becomes a requirement (and it's a big one I would say).

I listed Java as a perk of excelToCsv because once you have the JVM, any jar file should run without any other external dependency or compilation. In contrast to, say, python where the user may need to install some additional packages or C where you have to compile the source code yourself. In this respect, I'd say java programs are as self-contained as possible. You need the JVM, of course. But usually this is not an issue since there are freely available distributions for any operating system and no admin/root/superuser rights are required to install it.

I am going to close the issue now, but feel free to re-open it if you have any questions.

**Comment by Prid13** [comment]
@dariober Thanks for such an elaborate answer, really appreciate you taking the time to write it ⭐

That was an interesting read. I like the way you look at everything requiring _something_ at the end of the day, as it's definitely true. But to me, there's a difference between OS+pre-installed libraries/utilities VS installing additional tools. The OS is already there as part of your main use case for using a computer, while the JVM is most likely only installed if you're already invested or dealing with Java-related development.

The distinction is important because shipping this tool as part of a larger program would be difficult without requiring the end user to also have the JVM installed. My plan was to use this tool to compare some Excel files and make that tool available for other people, but I don't like asking end users to complete additional steps just to get to use a tool 😅 But that's just me :)

Sorry for posting an issue -- it was only meant as a comment, not an issue :) I have solved this via other tools (discovered the amazing self-contained **[`Qsv`](https://github.com/jqnatividad/qsv)** CLI tool that supports exporting an Excel to CSV), so no worries ⭐

**Comment by dariober** [comment]
Hi again - thanks for the pointer to qsv. I would point out, though, that as an Excel exporter qsv doesn't work as I would like and as a general user would expect. These are some examples from the test directory in excelToCsv. Consider the Excel file `test_data/dates.xlsx`:

![image](https://user-images.githubusercontent.com/6883382/193531081-3f8ab031-a470-4a10-a079-967abfa827ea.png)

qsv converts the dates to numeric (and I don't know why the first cell becomes `""`):

```
qsv excel test_data/dates.xlsx 2> /dev/null
""
43918.4861111111
12345.525
```

Instead, excelToCsv keeps them as dates as presented to the Excel user:

```
excelToCsv -p -i test_data/dates.xlsx 
21/03/20
28/03/20 11:40
18/10/1933 12:36:00
```

----

Here's another example (`test_data/format.xlsx`):

![image](https://user-images.githubusercontent.com/6883382/193535523-32428681-84d5-44f8-a3e8-a9c052473f6c.png)

I don't know what qsv is doing here:

```
qsv excel test_data/format.xlsx 2> /dev/null
bar,,,,,,,,,,,,,foo
```

compare to excelToCsv:

```
excelToCsv -p -i test_data/format.xlsx 
bar,2.66666156237642,5.33332312475284,60,0.0148290494731055,2.7,2.01E+02,-0.00360507125957782,0.000338847568184501,-0.0867370786746085,21/03/20,TRUE,123.00%,foo
```
or probably better use `-f` to avoid converting 200.666661562376 to 2.01E+02:

```
excelToCsv -f -p -i test_data/format.xlsx 
bar,2.66666156237642,5.33332312475284,60,0.0148290494731055,2.66666156237642,200.666661562376,-0.00360507125957782,0.000338847568184501,-0.0867370786746085,21/03/20,TRUE,1.23,foo
```

Eventually, I think Excel is better avoided to share data but I found my solution suites my needs better than what I found out there - happy to be proved wrong though!
